---
# geerlingguy.mac.homebrew
homebrew_cask_appdir: /Applications
homebrew_clear_cache: false
homebrew_upgrade_all_packages: true
homebrew_use_brewfile: false

homebrew_taps:
    - alehouse/homebrew-unofficial
    - alexdavid/homebrew-tap
    - homebrew/bundle
    - homebrew/cask
    - homebrew/cask-drivers
    - homebrew/cask-fonts
    - homebrew/command-not-found
    - homebrew/core
    - homebrew/services
    - iterative/homebrew-dvc
    - jzaleski/homebrew-jzaleski
    - teamookla/speedtest
homebrew_installed_packages: # Only include homebrew cask items here.
    - java
    - osxfuse
    - xquartz
    - 1password
    - 1password-cli
    - adobe-acrobat-reader
    - aerial
    - apppolice
    - apptrap
    - bartender
    - bbedit
    - bettertouchtool
    - betterzip
    - box-sync
    - cakebrew
    - cheatsheet
    - choosy
    - chrome-remote-desktop-host
    - coconutBattery
    - controlplane
    - cord
    - dash
    - daisydisk
    - dbeaver-community
    - dbvisualizer
    - diskmaker-x
    - docker
    - docker-toolbox
    - hpedrorodrigues/tools/dockutil
    - drivedx
    - dropbox
    - emacs
    - expressvpn
    - fantastical
    - filebot
    - firefox
    - flashlighttool
    - flux
    - font-jetbrains-mono-nerd-font
    - font-ntr
    - font-rubik
    - ganttproject
    - geektool
    - gephi
    - gimp
    - git-sizer
    - gmvault
    - goodsync
    - google-chrome
    - google-drive
    - go2shell
    - go64
    - gpg-suite
    - grammarly
    - grandperspective
    - ibettercharge
    - iina
    - imageoptim
    - imazing
    - install-disk-creator
    - intellij-idea-ce
    - intel-power-gadget
    - itch
    - iterm2
    - jing
    - jupyter-notebook-viewer
    - keka
    - keybase
    # - kindle  # Use mas instead
    - kitty
    - krisp
    - lastpass
    - lepton
    - lingon-x
    - macdown
    - mactex
    - makemkv
    - mark-text
    - mediainfo
    - meetingbar
    - menumeters
    - metaz
    - microsoft-office
    - monitorcontrol
    - muzzle
    - netnewswire
    - nightowl
    - no-ip-duc
    - omnidisksweeper
    - omnifocus
    - onyx
    - openaudible
    - oversight
    - pacifist
    - plantronics-hub
    - pocket-casts
    - podcastmenu
    # - prey  # Need to nstall separately with correct API key.
    - qlcolorcode
    - qlmarkdown
    - qlprettypatch
    - qlstephen
    - quicklook-csv
    - quicklook-json
    - raindropio
    - raycast
    - roaringapps
    - send-to-kindle
    - signal
    - silverlight
    - skyfonts
    - skype
    - slack
    - slimbatterymonitor
    - soundcloud-downloader
    - sourcetrail
    - sourcetree
    - spectacle
    - spotify
    - steamcmd
    - stretchly
    - sublime-text
    - suspicious-package
    - the-unarchiver
    - tigervnc-viewer
    - tripmode
    - typora
    - ultimaker-cura
    - unclack
    - upic
    - virtualbox
    - virtualbox-extension-pack
    - vlc
    - webpquicklook
    - xquartz
    - yubico-authenticator
    - yubico-yubikey-manager
    - yubico-yubikey-personalization-gui
    - yubico-yubikey-piv-manager
homebrew_uninstalled_packages:
    - diskwave
    - handylock
    - joplin
    - macfusion
# Don't use these.
homebrew_cask_apps: []
homebrew_cask_uninstalled_apps: []
