---
    - homebrew:
          name: [ruby]
          state: present

    - name: Install latest available version of global ruby packages.
      community.general.gem:
          name: {{item: null}: null}
          state: latest
  # command: gem install {{ item }}
      with_items: '{{ ruby_install_gems }}'
