---
- homebrew:
    name: "{{ item.name }}"
    state: present
  with_items:
    - ruby

- name: Install global ruby packages.
  command: gem install {{ item.name }}
  with_items: "{{ ruby_install_gems }}"
