---
    - name: Check ruby is installed and updated
      community.general.homebrew:
          name: [ruby]
          state: latest

    - name: Install latest available version of global ruby packages
      community.general.gem:
          name: '{{ item }}'
          user_install: no
          state: latest
      # command: gem install {{ item }}
      with_items: '{{ ruby_install_gems }}'

    - name: Cleanup gems
      shell: gem cleanup  # Do I need `yes n | gem cleanup` here?
      become: false
