---
additional-dependency-files:
    - type: pip-requirements-txt
      path: requirements-dev.txt

ignore-failures:
    python:
        - alabaster
        - astor
        - astunparse
        - async-generator
        - async-timeout
        - backcall
        - blinker
        - click-completion
        - click-configfile
        - click-default-group
        - click-didyoumean
        - click-log
        - click-man
        - click-repl
        - click-spinner
        - click-threading
        - commonmark
        - cycler
        - doublemetaphone
        - entrypoints
        - future
        - google-pasta
        - imagesize
        - iniconfig
        - ipython-genutils
        - jupyter
        - jupyter-contrib-core
        - jupyter-contrib-nbextensions
        - keras-preprocessing
        - markupsafe
        - mccabe
        - mistune
        - opt-einsum
        - patsy
        - pexpect
        - pickleshare
        - probableparsing
        - probablepeople
        - pyasn1
        - pyasn1-modules
        - pylev
        - pytz-deprecation-shim
        - semver
        - send2trash
        - sklearn
        - sphinxcontrib-applehelp
        - sphinxcontrib-devhelp
        - sphinxcontrib-jsmath
        - sphinxcontrib-qthelp
        - termcolor
        - testpath
        - toml
        - vobject
        - wcwidth
        - webencodings
        - widgetsnbextension

    ruby:
        - bundle-audit
        - jekyll-gist
        - jekyll-github-metadata
        - jekyll-include-cache
        - jekyll-paginate
        - jekyll-sitemap
        - jemoji
        - mdl
        - ruby-lint
        - terminal-notifier
        - wdm
