---
# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
BASH_SHELLCHECK_ARGUMENTS: '--external-sources --format=gcc --shell=bash'
DISABLE:
  - ACTION # FIXME: Figure out why doesn't run!
  - EDITORCONFIG # FIXME: Figure out why not working!?
  - PYTHON
DISABLE_LINTERS:
  - BASH_SHELLCHECK # FIXME: Related to ACTION error?
  - COPYPASTE_JSCPD
  - C_CPPLINT
  - REPOSITORY_DEVSKIM
  - RST_RSTCHECK
  - RST_RST_LINT
  - SQL_TSQLLINT
FILEIO_REPORTER: true
JAVASCRIPT_PRETTIER_FILTER_REGEX_EXCLUDE: .cache # FIXME: DOESN'T WORK?!
JSON_V8R_DISABLE_ERRORS: true
LINTER_RULES_PATH: .
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: .cache
MARKDOWN_MARKDOWN_LINK_CHECK_FILTER_REGEX_EXCLUDE: .cache
SHOW_ELAPSED_TIME: true
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: .cache
