# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/brigade/overcommit/blob/master/config/default.yml
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre-commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/brigade/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/brigade/overcommit#configuration
#
# required:     If true, this hook cannot be skipped via the SKIP
#               environment variable
# quiet:        If true, this hook does not display any output unless
#               it warns/fails
# description:  Message displayed while hook is running.
#
# Within a hook category, there is a special type of hook
# configuration that applies to all hooks in the category. This
# configuration looks like a normal hook configuration, except it has
# the name ALL:
#
# PreCommit:
#   ALL:
#     problem_on_unmodified_line: warn
#     requires_files: true
#     required: false
#     quiet: false
#
# SKIP=RuboCop git commit
# ONLY=RuboCop git commit
# OVERCOMMIT_DISABLE=1 ./my-custom-script

---
CommitMsg:
  HardTabs:
    enabled: true
  MessageFormat:
    enabled: false
    pattern: '\[#(\d+)\](.+)'
    expected_pattern_message: '[#<Issue Id>] <Commit Message Description>'
    sample_message: '[#1234] Refactored Onboarding flow'
  RussianNovel:
    enabled: true
  SpellCheck:
    enabled: true
    install_command: 'brew install hunspell'
  TextWidth:
    enabled: true
    max_subject_width: 50

PreCommit:
  ALL:
    # report: report errors/warnings as-is regardless of line location (default)
    # warn: report errors as warnings if they are on lines you didn't modify
    problem_on_unmodified_line: warn
  BashSyntax:
    enabled: true
    quiet: false
    include: '**/*.sh'
    required_executable: 'bash-syntax'
  BrokenSymlinks:
    enabled: true
  BundleAudit:
    enabled: true
  BundleCheck:
    enabled: true
  BundleOutdated:
    enabled: true
  CaseConflicts:
    enabled: true
  CopyrightYear:
    enabled: true
    quiet: false
    required_executable: 'copyright-year'
  CssLint:
    enabled: true
  Eslint:
    enabled: true
  ExecutePermissions:
    enabled: true
    exclude:
      - 'bin/**/*'
      - 'ci/*.sh'
  Fasterer:
    enabled: true
  FixMe:
    enabled: true
    exclude:
      - 'notebooks/**/*.ipynb'
  ForbiddenBranches:
    enabled: false
  Flay:
    enabled: true
  GoLint:
    enabled: true
  GoVet:
    enabled: true
  Hadolint:
    enabled: true
  HamlLint:
    enabled: true
  HardTabs:
    enabled: true
  HtmlHint:
    enabled: true
  HtmlTidy:
    enabled: true
  ImageOptim:
    enabled: true
  JavaCheckstyle:
    enabled: true
  Jscs:
    enabled: true
  JsHint:
    enabled: true
  JsLint:
    enabled: true
  JsonSyntax:
    enabled: true
  LicenseFinder:
    enabled: false
  LicenseHeader:
    enabled: false
    license_file: 'LICENSE'
    include: '**/*.py'
  # Requires overcommit have access to git version 2.10 or higher.
  LineEndings:
    enabled: true
  LocalPathsInGemfile:
    enabled: true
  Markdownlint:
    enabled: true
    required_executable: 'markdownlint'
  Mdl:
    enabled: true
  Pycodestyle:
    on_fail: 'warn'
    enabled: true
    flags:
      # E703 statement ends with a semicolon.
      # Need for matplotlib in Jupyter notebooks.
      - '--ignore=E211,E231,E703,W291,W293'
      - '--max-line-length=120'
      # - '--show-source'  # Don't use!
    exclude:
      - 'jupyter/jupyter_notebook_config.py'
      - 'setup.py'
  Pydocstyle:
    enabled: true
    flags:
      - '--ignore=D100,D103,D203'
    exclude:
      - 'jupyter/jupyter_notebook_config.py'
  Pyflakes:
    enabled: false
  Pylint:
    enabled: true
    flags:
      - '--max-line-length=120'
      - '--msg-template="{path}:{line}:{C}: {msg} ({symbol})"'
      - '--reports=n'
      - '--persistent=n'
    exclude:
      - 'jupyter/jupyter_notebook_config.py'
      - 'setup.py'
  PythonFlake8:
    enabled: true
    flags:
      - '--doctests'
      - '--exclude =.git,__pycache__'
      - '--ignore=F401,F403,F405'
      - '--max-complexity=10'
      - '--max-line-length=120'
      - '--select=E10,E11,E9,F4,F6,F7,F8'
      - '--show-source'
    exclude:
      - 'jupyter/jupyter_notebook_config.py'
      - 'setup.py'
  Reek:
    enabled: true
  RstLint:
    enabled: true
  RuboCop:
    enabled: true
  RubyLint:
    enabled: true
    exclude: '**/.mdl.rb'
  Safety:
    enabled: true
    required_executable: 'safety.sh'
  Scalariform:
    enabled: false
  Scalastyle:
    enabled: false
    flags: ['-c', '.idea/scalastyle-config.xml']
  SemiStandard:
    enabled: true
  Standard:
    enabled: true
  ShellCheck:
    enabled: true
    flags:
      - '--format=gcc'
      - '--external-sources'
      - '--shell=bash'
  Sqlint:
    enabled: false
  ToDos:
    enabled: false
    quiet: false
    required_executable: 'check-todos'
  TrailingWhitespace:
    enabled: true
  TravisLint:
    enabled: true
  Vint:
    enabled: true
  W3cCss:
    enabled: true
  W3cHtml:
    enabled: true
  XmlLint:
    enabled: true
  XmlSyntax:
    enabled: true
  YamlLint:
    enabled: true
    flags:
      - '--config-data "{extends: default, rules: {line-length: {max: 120}}}"'
  YamlSyntax:
    enabled: true
    include:
      - '**/*.yaml'
      - '**/*.yml'
      - '**/.*.yml'  # To parse this!
  YardCoverage:
    enabled: false

PostCheckout:
  BundleInstall:
    enabled: true
  GitLfs2:
    enabled: true
    command: ['git', 'lfs', 'post-checkout']
  IndexTags:
    enabled: true
  SubmoduleStatus:
    enabled: true
    quiet: false
    recursive: true

PostCommit:
  BundleInstall:
    enabled: true
  GitGuilt:
    enabled: true
    requires_files: false
  GitLfs2:
    enabled: true
    command: ['git', 'lfs', 'post-commit']
  SubmoduleStatus:
    enabled: true
    quiet: false
    recursive: true

PostMerge:
  BundleInstall:
    enabled: true
  GitLfs2:
    enabled: true
    command: ['git', 'lfs', 'post-merge']
  IndexTags:
    enabled: true
  SubmoduleStatus:
    enabled: true
    quiet: false
    recursive: true

PostRewrite:
  BundleInstall:
    enabled: true
  IndexTags:
    enabled: true
  SubmoduleStatus:
    enabled: true
    quiet: false
    recursive: true

PrePush:
  GitLfs2:
    enabled: true
    command: ['git', 'lfs', 'pre-push']
  ProtectedBranches:
    enabled: true
  Pytest:
    enabled: false
  PythonNose:
    enabled: false

PreRebase:
  MergedCommits:
    enabled: true

PreReceive:
  FreeSpace:
    enabled: true
    quiet: false
    required_executable: 'check-freespace'
