---
default_install_hook_types:
    - commit-msg
    - prepare-commit-msg
    - pre-commit
    - pre-merge-commit
    - pre-push
    - pre-rebase
    - post-checkout
    - post-commit
    - post-merge
    - post-rewrite

repos:
    # General

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-toml
          - id: check-xml
          - id: check-yaml
          - id: detect-private-key
          - id: double-quote-string-fixer
          - id: end-of-file-fixer
          - id: mixed-line-ending # Replaces or checks mixed line ending.
          - id: trailing-whitespace

    - repo: https://github.com/asottile/add-trailing-comma
      rev: v3.1.0
      hooks:
          - id: add-trailing-comma
            args:
                - --py36-plus

    - repo: https://github.com/Yelp/detect-secrets
      rev: v1.5.0
      hooks:
          - id: detect-secrets
            args: [--baseline, .secrets.baseline]
            exclude: package.lock.json

    - repo: https://github.com/sirosen/texthooks
      rev: 0.6.8
      hooks:
          - id: fix-smartquotes
          - id: fix-ligatures

    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: forbid-binary
          - id: git-check # Configure in .gitattributes
          - id: shellcheck
            args: [--external-sources, --format=gcc, --shell=bash]
          - id: shfmt

    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.5.5
      hooks:
          - id: remove-crlf
          - id: remove-tabs
            exclude: .git/COMMIT_EDITMSG

    - repo: https://github.com/sirosen/check-jsonschema
      rev: 0.33.0
      hooks:
          - id: check-github-actions
          - id: check-github-workflows
          - id: check-readthedocs

    - repo: https://github.com/zricethezav/gitleaks
      rev: v8.25.1
      hooks:
          - id: gitleaks

    - repo: https://github.com/rhysd/actionlint
      rev: v1.7.7
      hooks:
          - id: actionlint

    - repo: https://github.com/lycheeverse/lychee.git
      rev: lychee-v0.18.1
      hooks:
          - id: lychee
            args: ["--cache", "--suggest"]

    # Markdown

    - repo: https://codeberg.org/frnmst/md-toc
      rev: 9.0.0
      hooks:
          - id: md-toc
            args: [--in-place, --no-indentation, github]

    # YAML

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.37.1
      hooks:
          - id: yamllint
            args: [-c=.yamllint.yml]

    # Do after md_toc

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v4.0.0-alpha.8
      hooks:
          - id: prettier
            stages: [pre-commit]

    # Do after prettier

    - repo: https://github.com/proinsias/mado
      rev: 1.0.0
      hooks:
          - id: mado
