---
sudo: required
language: objective-c
# 10.14 (see https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version)
osx_image: xcode10.2

# matrix:
 # fast_finish: true
 # include:
   # - env: TAGS=homebrew,macdock,macos,macos-standby,nodejs,osx-defaults,osx-user-picture,pipx,ruby,travis
   # - env: TAGS=mas,travis  # mas has automation issues.

cache:
  apt: true
  ccache: true
  bundler: true
  pip: true
  directories:
    - "${HOME}/.cache"   # cython cache
    - "${HOME}/.ccache"  # compiler cache
    - "${HOME}/.pip-cache"
    - "${HOME}/Library/Caches/Homebrew"
    - "/etc/ansible/roles"
    - "node_modules"  # npm packages

before_install:
  # Uninstall existing Homebrew installation, if necessary.
  - |
    curl --location --remote-name --silent https://raw.githubusercontent.com/Homebrew/install/master/uninstall
    chmod +x ./uninstall
    ./uninstall --force
    sudo rm -rf /usr/local/Homebrew
    sudo rm -rf /usr/local/Caskroom
    sudo rm -rf /usr/local/bin/brew
    # if test $TAGS = 'homebrew'; then
    # fi


install:
  # Install and configure Ansible.
  - "./bin/setup_ansible.sh"

  # Install dependencies.
  - "./bin/install_dependencies.sh"

  # Install aerial screensaver, if necessary.
  # - |
  #   if [[ "${TAGS}" == *"macos"* ]]; then
  #       brew cask install aerial
  #   fi

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook --syntax-check main.yml"

  # Test the playbook, tag by tag
  - "travis_wait 30 ./bin/travis_all_tags.sh"

before_cache:
  - brew cleanup
  - rm -f "${HOME}/.cache/pip/log/debug.log"

notifications:
  slack:
    # yamllint disable-line rule:line-length
    secure: Mf5gMiO9dpeIYLmhju/GkpZh0rlOu5a6uxOJlCggFSEjTsUZXYw8mzmCrO5T0CfJtGYRrf22oLFEVqAZEEzGAFQxdYMMUbONLnbiG2ueMRHLx+xKlipNlOmj3Hx0/s9vq5koLHU0penLfH1zkRy8i4f972MPpvHFMlFmMH1lfUR+MaIcxAXr1ntErPod0ZzZBJZVuQj4Z2f+SwhIzsWQAUfWiIu+a0t/N0a43liW4EC3MvxSkKL419IPpja4vMQNBKvXS08Qzx5zfqyOxeTMxv0okm/AlT7ASNoMy3tXe0PrqVX7Ntrb7t6n/mc62jpMcjzAij3uzdk8Juza31q+1aZ5guJq/bArt93qpDZ0oF0liPpYt9ZKyVq8yTfEdmID+dDM1dXPyBcYgCkOxuE5rhTVV6gyJ7i9kjHuWYjiuXW/9wlfrhNMSkpvDjjWw5DL1j///V27o3lkQ17naVBmLTb72G47RXAuet7RYXyv63tHeJ/IvvCQUjQRYQPHbyiPpgtBe3BaGF62Wxti8Jmt+D3wz5YIOKLHet7QnE4mDGG5GtsbhcO1PKNWnQ3OGSGNy9LPoiJBcKK5fXFf/Y5PvjhbHl0b5TwFXknBEuFU37zNK19quxZY5MjSxYZ1g/dUkOsv4u5Pg0vkb4xVymAaLmM3PBLAIcXyv5X08Ecog/g=
