---
sudo: required
language: objective-c
# 10.14 (see https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version)
osx_image: xcode10.2

matrix:
  fast_finish: true
  include:
    - env: TAGS=extra-packages,macos,osx-defaults
    - env: TAGS=homebrew
    # - env: TAGS=mas  # mas has automation issues.

cache:
  apt: true
  ccache: true
  custom_install: true  # Since we override the default install command.
  bundler: true
  pip: true
  directories:
    - "${HOME}/.cache"   # cython cache
    - "${HOME}/.ccache"  # compiler cache
    - "${HOME}/.pip-cache"
    - "${HOME}/Library/Caches/Homebrew"
    - "/etc/ansible/roles"
    - "node_modules"  # NPM packages

before_install:
  # Uninstall existing Homebrew installation.
  - >
    if test $TAGS = 'homebrew'; then
        curl --location --remote-name --silent https://raw.githubusercontent.com/Homebrew/install/master/uninstall
        chmod +x ./uninstall
        ./uninstall --force
        sudo rm -rf /usr/local/Homebrew
        sudo rm -rf /usr/local/Caskroom
        sudo rm -rf /usr/local/bin/brew
    fi
  - >
    if [[ "${TAGS}" == *"macos"* ]]; then
        # We need to ensure aerial screensaver is installed.
        brew cask install aerial
    fi

install:
  - "./bin/setup_ansible.sh"

script:
  # Install dependencies.
  - "ansible-galaxy install --role-file requirements.yml"

  # Check the role/playbook's syntax.
  - "ansible-playbook main.yml --syntax-check"

  # Copy test config.yml into place.
  - "cp tests/config.yml config.yml"

  # Test the playbook, tag by tag
  - "travis_wait 30 ansible-playbook main.yml --inventory inventory --tags ${TAGS}"

before_cache:
  - brew cleanup
  - rm --force "${HOME}/.cache/pip/log/debug.log"

notifications:
  slack:
    # yamllint disable-line rule:line-length
    secure: PDtcvz//in9jj9g96rjAePhb59NizHGxrPZpmVXvYLNuYh2iN4i9GgBruLoySS5pg4cALgs69quof9c6lF8U75w0FfcOxfANb+6Y5Joh/uvR7IhPe9rZjadsXG4kNlSwfTcxMOc9mTHmyKi50WcnwWGVjPAU8uKnlUPxV3K3kjeuKD6QDOJuCtKgTKyeW92VvtMAKILBD+UOrkdr72eCwtQ+cReQ2JNgYndRgjcs6TxDRAq2OISrHSyX7/ISfqvHcOCnH8jazSFYbYcTZ7Sk9CnDGt+FDz+e8hNysI5T8sFGge6eiwyJQ7ivqdvbWYKS0AFeJA8BQwbrA7gt6jLaM5v5WLY7npVMAhkwtM2s6/Z2p1IsEqhaigoLINfyBw6MCbIDeZg1OJdocuWRNE+pfZgVXzC2XXcnbg+u5ChaqgqoKqN3/Y+W0IGZ4AXXWcT1XHVgB414j4TZ+t/bIlKMbcdD4n9tvmV9+zm+bZ8keFkWlMSac4bW7wX9gOQG4FMUGolznTinwlAwpCpjP22gM7M6BoDwg2URWE5qcXoJYERHdsvaOAOTlj3RnnBjsVZwbIfk2gbWmE0aKwk8l21PBhjiBsZvHPyBR6EeAUi8bktQUfdAImk53h0GYPeSJ6ocu8fas8NgBuZf5Ysc0RxQYnQUkqZZBO53BOScDr87tHE=
