---
downloads: ~/.ansible-downloads/

#homebrew_installed_packages:
#  # - ansible # Installed via Pip.
#  - bash-completion
#  - git
#  - go
#  - gpg
#  - hub
#  - httpie
#  - node
#  - ssh-copy-id
#  - cowsay
#  - readline
#  - openssl
#  - pv
#  - wget
#
#homebrew_taps:
#  - homebrew/core
#  - homebrew/cask
#
#homebrew_cask_appdir: /Applications
#homebrew_cask_apps:
#  - docker
#  - dropbox
#  - google-chrome
#  - handbrake
#  - slack
#
## See `geerlingguy.mas` role documentation for usage instructions.
#mas_installed_apps: []
#mas_email: ""
#mas_password: ""

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
gem_packages: []
npm_packages: []
pip_packages: []

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
