source 'https://rubygems.org'
gem 'bundler'
gem 'bundler-audit'
gem 'danger'
gem 'fasterer'
gem 'mdl'
gem 'overcommit', '>= 0.41.0'
gem 'reek'
gem 'rubocop'
gem 'rubocop-performance'
gem 'ruby-lint'
gem 'travis', '>= 1.8.8'
