source 'https://rubygems.org'
gem 'bundler'
gem 'bundler-audit'
gem 'danger', '>= 8.4.2'
gem 'fasterer'
gem 'mdl', '>= 0.11.0'
gem 'reek'
gem 'rubocop'
gem 'rubocop-performance'
gem 'ruby-lint'
gem 'travis', '>= 1.9.0'
