source 'https://rubygems.org'
gem 'bundler'
gem 'bundler-audit'
gem 'danger', '>= 9.4.3'
gem 'fasterer'
gem 'mdl', '>= 0.11.0'
gem 'reek'
gem 'rubocop', '>= 1.8.0'
gem 'rubocop-performance', '>= 1.20.0'
gem 'ruby-lint'
