---
- hosts: all
  connection: local
  gather_facts: true

  tasks:
    # - name: print facts
    #   debug:
    #     var: ansible_facts
    - name: Run ilovemovies role.
      include_role:
        name: ilovemovies
        apply:
          tags: ['ilovemovies', 'never']
      tags: ['ilovemovies', 'never']  # This won't run unless you specify the 'ilovemovies' tag.

    - name: Run ospideal role.
      include_role:
        name: ospideal
        apply:
          tags: ['ospideal', 'never']
      tags: ['ospideal', 'never']

    - name: Run travis role.
      include_role:
        name: travis
        apply:
          tags: ['travis', 'never']
      tags: ['travis', 'never']

    - name: Run all role.
      include_role:
        name: all
      tags: ['always']

# FIXME: GT TGT folder
