---
- hosts: all
  connection: local

  vars_files:
    - vars/mas.yml  # geerlingguy.mas
    - vars/macos.yml  # kinglouie.macos
    - vars/osx-defaults.yml  # lafarer.osx-defaults
    # - vars/pip.yml  # geerlingguy.pip
    # - vars/ruby.yml  # geerlingguy.ruby
    # - npm packages?

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']
    - role: kinglouie.macos
      tags: ['macos']
    - role: lafarer.osx-defaults
      tags: ['osx-defaults']

  tasks:
    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - include_tasks: tasks/homebrew.yml
      tags: ['homebrew']

    - include_tasks: tasks/homebrew-cask.yml
      tags: ['homebrew-cask']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
