---
- hosts: firefly.local
  connection: local

  vars_files:
    - vars/homebrew.firefly.yml  # geerlingguy.homebrew
    - vars/mas.firefly.yml  # geerlingguy.mas

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']

- hosts: ospideal.local
  connection: local

  vars_files:
    - vars/homebrew.ospideal.yml  # geerlingguy.homebrew
    - vars/mas.ospideal.yml  # geerlingguy.mas

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']

- hosts: travis.dev  # FIXME: Pick one.
  connection: local

  vars_files:
    - vars/homebrew.travis.yml  # geerlingguy.homebrew

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']

- hosts: Traviss-Mac.local  # FIXME: Pick one.
  connection: local

  vars_files:
    - vars/homebrew.travis.yml  # geerlingguy.homebrew

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']

- hosts: all
  connection: local

  vars_files:
    - vars/homebrew.yml  # geerlingguy.homebrew
    - vars/mas.yml  # geerlingguy.mas
    - vars/macos.yml  # kinglouie.macos
    - vars/osx-defaults.yml  # lafarer.osx-defaults
    # FIXME: Add tags below.
    # - vars/pip.yml  # geerlingguy.pip
    # - vars/ruby.yml  # geerlingguy.ruby
    # - npm packages?

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew', 'always']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']
    # FIXME: Why broken?
    # - role: kinglouie.macos
    #   tags: ['macos']
    - role: lafarer.osx-defaults
      tags: ['osx-defaults']

    # # FIXME: Put macos_power_settings in var file?
    # - {role: appian.macos-power,
    #    become: yes,
    #    macos_power_settings: [
    #      {cmd: computersleep, desired_value: 'Never'},
    #      {cmd: displaysleep, desired_value: 'after 15 minutes'},
    #      {cmd: harddisksleep, desired_value: 'Never'},
    #      {cmd: restartfreeze, desired_value: 'Off'},
    #      {cmd: wakeonnetworkaccess, desired_value: 'On'},
    #    ]
    # }
    # - geerlingguy.nodejs
    # - geerlingguy.pip
    # - geerlingguy.ruby

  tasks:
    # - name: print facts
    #   debug:
    #     var: ansible_facts

    # FIXME: Replace with geerlingguy.pip/geerlingguy.ruby/npm ???
    - include_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    # FIXME: GT this and roles directory!
    # - include_role:
    #     name: darwin
    #   when: ansible_facts['os_family']|lower == 'darwin'
    # - include_role:
    #     name: debian
    #   when: ansible_facts['os_family']|lower == 'debian'
    # - include_role:
    #     name: redhat
    #   when: ansible_facts['os_family']|lower == 'redhat'
    # - include_role:
    #     name: common

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"


# FIXME: Cheatsheet installed via cask **and** mas?

# FIXME: Test using tags to limit what we use
#  - for testing
#  - for running all the "update" tasks like brewup etc
# FIXME: How report newly installed brews, casks, pips, npms, gems, etc. that aren't in this file.


# FIXME: Add:
# sudo echo /usr/local/bin/bash >> /etc/shells
# npm install -g git-guilt
# gem install bundler
# gem install bundler-audit

# FIXME: Add installation of bashhub - via pipx?

# FIXME: ansible-role-dotfiles!

# FIXME: GT FIXMEs in:
#./roles/darwin/vars/main.yml:  ComputerName: "discovery"  # osx-computername # FIXME: Set per computer, or use to identify host!
# https://github.com/lafarer/ansible-role-osx-computername/blob/master/tasks/main.yml

# FIXME: Move brewup, gemupdate to here?

# FIXME: Eventually Look up roles for redhat/debian stuff similar to macos stuff

# FIXME: Can use same tag on multiple tasks to group tasks.

# FIXME: Can use prompts

# FIXME:
#
# https://github.com/fubarhouse/ansible-role-macdock
# https://github.com/danbohea/ansible-role-macos-dock
# https://galaxy.ansible.com/danbohea/flux - flux configuration?
# https://galaxy.ansible.com/shashikant86/ios-dev
# ansible Liquid Prompt ala drew-kun/ansible-ohmyzsh
# https://galaxy.ansible.com/bjoernalbers/sysctl
#https://github.com/feffi/ansible-macos-softwareupdate
#https://github.com/dotstrap/ansible-xcode
#https://github.com/ansible/ansible-modules-extras/blob/devel/system/osx_defaults.py
#
#https://github.com/mego22/ansible-role-osx-settings
#
#https://github.com/0x4e3/osx-bootstrap-defaults
#https://github.com/osxstrap/ansible-osx-user-picture
# https://en.gravatar.com/userimage/34741261/b37d9ade8b8cea564bc47268db650c84.jpg?size=200
#https://github.com/osxstrap/ansible-osx-software-update
# drew-kun/ansible-dnscrypt
# drew-kun/ansible-sshd
# drew-kun/ansible-macos_terminal

#all:
# https://github.com/feffi/ansible-macos-git-repos

#darwin:
# https://github.com/feffi/ansible-macos-standby

#darwin/firefly:
# https://github.com/feffi/ansible-macos-timemachine



# FIXME: Use roles and separate files to setup mac/ubuntu/centos machines.
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html
# Or maybe different things via ansible galaxy?
# See
# https://github.com/lafarer/ansible-role-osx-defaults/blob/18072c8e68afb2e2244825ad1a6f42affd75f1ed/tasks/main.yml

# FIXME: Can use same tag on multiple tasks to group tasks.

# FIXME: Can use prompts

# FIXME:
# ansible-role-pip
# ansible-role-dotfiles
# https://github.com/danbohea/ansible-role-rbenv
# https://github.com/fubarhouse/ansible-role-macdock
# https://github.com/danbohea/ansible-role-macos-dock
# https://galaxy.ansible.com/danbohea/flux - flux configuration?
# https://galaxy.ansible.com/shashikant86/ios-dev
# https://galaxy.ansible.com/drew-kun/macos_terminal
# https://galaxy.ansible.com/mhalano/dropbox
# https://galaxy.ansible.com/bjoernalbers/sysctl
#https://github.com/juju4/ansible-harden-darwin
#https://github.com/feffi/ansible-macos-softwareupdate
#https://github.com/dotstrap/ansible-xcode
#https://github.com/ansible/ansible-modules-extras/blob/devel/system/osx_defaults.py
#
#https://github.com/mego22/ansible-role-osx-settings
#https://github.com/lafarer/ansible-role-osx-jenv
#https://github.com/fubarhouse/ansible-role-macfonts
#https://github.com/0x4e3/osx-bootstrap-defaults
#https://github.com/osxstrap/ansible-osx-user-picture
#https://github.com/osxstrap/ansible-osx-software-update
#https://github.com/feffi/ansible-macos-git-repos
#https://github.com/feffi/ansible-macos-timemachine
#https://github.com/feffi/ansible-macos-standby
#https://github.com/openstack/ansible-hardening

# FIXME:
# https://stackoverflow.com/questions/25230376/how-to-automatically-install-ansible-galaxy-roles
# When creating galaxy requirements, specify hash so they are pinned!


# FIXME: Add pipx,
# FIXME: GT .bashrc .profile.
