---
    - homebrew:
          name: [python, pipx]
          state: present

    - name: Install global pipx packages.
      command: pipx install {{ item }} --python /usr/local/bin/python3
      with_items: '{{ pipx_packages }}'

    - name: Install global pipx flake8 packages.
      command: pipx inject flake8 {{ item }}
      with_items: '{{ pipx_flake8_packages }}'

    - name: Install global pipx mdformat packages.
      command: pipx inject mdformat {{ item }}
      with_items: '{{ pipx_mdformat_packages }}'

    - name: Install global pipx ntfy packages.
      command: pipx inject ntfy {{ item }}
      with_items: '{{ pipx_ntfy_packages }}'

    - name: Install global pipx pydocstyle packages.
      command: pipx inject pydocstyle {{ item }}
      with_items: '{{ pipx_pydocstyle_packages }}'

    - name: Install global pipx pytest packages.
      command: pipx inject pytest {{ item }}
      with_items: '{{ pipx_pytest_packages }}'
