---
system:
  ui:
    # Overall system interface color
    # This influences Menubar, Dock, Spotlight and a few others.
    # VALUES: "Light", "Dark"
    interface_style: "Dark"

    # By default the macOS save/print dialog opens in a simplified version.
    # Enable to show the full dialog by default.
    expand_save_panel: true
    expand_print_panel: true

    # Window action when double clicking on the titlebar of a window.
    # VALUES: "Maximize", "Minimize"
    # titlebar_doubleclick_action: "Maximize"

    # Font smoothing on non apple displays
    enable_subpixel_font_rendering: true

    # Focus ring is drawn around focused dialog
    # elements like buttons and textfields
    # enable_focus_ring: true

    # macOS ommits common file extensions by default.
    show_all_file_extensions: true

    # Antique osx dashboard, this was more or less replaced by the sidebar.
    disable_dashboard: true

    # Open directory if you drag a file/folder onto it.
    enable_springloading_directories: true
    springloading_directories_delay: 0

    window_resize_speed: 0.001
    enable_opening_closing_window_animations: false

    # Show scrollbars
    # Values: "WhenScrolling", "Always"
    show_scrollbars: "Always"

    enable_menubar_transparency: false

screensaver:
  # Screensaver activation delay in seconds
  # 0 disables the screensaver
  activation_delay: 300

  # Ask for user password when screensaver is active
  ask_password: true

  # Delay in seconds after which password is asked
  ask_password_delay: 0

  screensaver:
    name: Aerial
    path: ~/Library/Screen Savers/Aerial.saver

input:

  # Various spell correction settings
  enable_auto_correct: true
  enable_smart_quotes: false
  enable_smart_dashes: false
  # enable_automatic_capitalization: yes
  # enable_automatic_periods: yes
  enable_continuous_spell_checking: true

  # If enabled, you get a special char menu on certain letters instead of key repeat
  # enable_press_and_hold: yes

  # Key repeat speed
  # Min value is 1
  # key_repeat_rate: 2

  # Delay time until key repeat kicks in
  # initial_key_repeat_delay: 22

  # Enables selections of dialog buttons with tab key
  enable_full_keyboard_access: true

  # Space switching hotkeys (ctrl + 1-9)
  # enable_space_hotkeys: no

# hostname:
# computername is the so-called “user-friendly” name for the Mac,
# it’s what will show up on the Mac itself and what will be
# visible to others when connecting to it over a local network.
# This is also what’s visible under the Sharing preference panel.
# computername: null

# hostname is the name assigned to the computer as visible
# from the command line, and it’s also used by local and
# remote networks when connecting through SSH and Remote Login.
# hostname: null

# localhostname is the name identifier used by Bonjour and
# visible through file sharing services like AirDrop
# localhostname: null

security:
  # Gatekeeper won't allow you to easily install
  # unsigned apps not downloaded from the Mac App Store
  enable_gatekeeper: true

  # Quarantine asks you if you really want
  # to open a downloaded executable
  enable_quarantine: true

misc:

  save_application_state_on_quit: true

  disable_dsstore_on_network_shares: true

  disable_dsstore_on_usb_drives: true

  disable_disk_image_verification: true

  disable_spotlight_network_indexing: true

  save_new_docs_to_icloud: false

  enable_ssh: false  # true causes failure on latest macos versions.

  enable_crash_reporter: true

  enable_startup_sound: false

  enable_sudden_motion_sensor: false  # Not useful for SSDs

  enable_hibernation: false

  # Default filetype <-> app associations
  # Values:
  #   extension: file extension
  #   handler: application bundle identifier
  # Example:
  #   default_applications:
  #     - { extension: avi, handler: com.colliderli.iina }
  # default_applications: []


######################################
#               Finder               #
######################################

finder:

  # Default location for new finder windows/tabs.
  # VALUES: "PfHm" for homedir, "PfDe" for desktop,
  # For other paths, use `PfLo` and `file:///full/path/here/`
  # May need to set NewWindowTargetPath too.
  new_window_target: "PfDe"

  # Finder warns when you are changing a file extension.
  show_file_extensions_warning: false

  warn_before_emptying_the_trash: true

  # Should dotfiles be shown?
  # "cmd + shift - ." toggles this
  show_all_files: true

  # Keep folders on top when you sort by name?
  keep_folders_on_top: false

  # Show posix path in finder titlebar?
  show_full_path_in_titlebar: true

  # Show interactive pathbar at the bottom?
  show_pathbar: true

  # Show statusbar with selection and filesize info at the bottom?
  show_statusbar: true

  # Should finder be quitable? (It instantly restarts anyway)
  enable_quit_menu_item: true

  # VALUES: "icnv" for icon view, "clmv" for column view, "Flwv" for cover flow view
  # 'Nlsv' for ?.
  default_view_style: "clmv"


  # Which items should be shown on desktop?
  show_external_harddrives_on_desktop: true
  show_harddrives_on_desktop: true
  show_mounted_servers_on_desktop: true
  show_removable_media_on_desktop: true

  # Hide ~/Library ?
  hide_user_library: false

  # Hide /Volumes ?
  hide_system_volumes: false

  # Which panes of the Getinfo window should be expanded by default?
  expand_infopane:
    - { name: General , value: true }
    # - { name: MetaData , value: false }
    - { name: OpenWith , value: false }
    # - { name: Name , value: false }
    # - { name: Comments , value: false }
    # - { name: Preview , value: true }
    - { name: Privileges , value: false }

  # Automatic arrangement of icons
  # Values: "none", "grid", "name", "kind", "dateModified",
  #         "dateCreated", "dateLastOpened", "dateAdded", "size", "label"
  iconview_arrange_by: "grid"

  # controls the gap between icons
  # when using arrange by grid
  # iconview_grid_spacing: 54

  # Size of the icons
  # iconview_icon_size: 64

  # Show item info below item name?
  iconview_show_item_info: true

  # Font size
  # iconview_text_size: 12

  # Show item preview as icon? (mostly useful for images)
  # iconview_show_icon_preview: true

  # When disabled label is shown to the right of icons
  # iconview_show_label_on_bottom: true

  # Doesn't work on newer macOS versions
  # enable_quicklook_text_selection: false

  disable_all_animations: true


######################################
#               Safari               #
######################################

safari:

  show_full_url_in_address_bar: true

  open_safe_files_automatically: false

  enable_status_bar: true

  enable_developer_menu: true

  autofill_passwords: false

  show_favorites_bar: true

  disable_thumbnail_cache: false

  # search_with_word_start_only: true


######################################
#                Mail                #
######################################

mail:

  address_include_name_on_pasteboard: false


######################################
#              TextEdit              #
######################################

textedit:

  default_doc_plaintext: true


######################################
#              Terminal              #
######################################

terminal:

  enable_secure_keyboard_entry: true

######################################
#                Dock                #
######################################

dock:

  # icon size
  tile_size: 36

  show_idicator_lights: true

  hidden_items_translucent: true

  # fade_in_time: 0

  rearrange_spaces_by_last_use: false

  autohide: true

  # Use fubarhouse.macdock instead of below items.

  # if enabled configured apps will be added
  # even if they're not installed
  # apps_force_install: false

  # removes apps from the dock that are
  # not defined in the apps list
  # apps_remove_undefined: true

  # Apps to add to dock
  # example item:
  # - name: Safari
  #   path: /Applications/Safari.app
  # apps: []

  # Spacers to add to dock
  # example item:
  # - after: Safari
  #  spacers: []
