---
system:
  ui:
    # Overall system interface color
    # This influences Menubar, Dock, Spotlight and a few others.
    # VALUES: "Light", "Dark"
    interface_style: "Dark"

    # By default the macOS save/print dialog opens in a simplified version.
    # Enable to show the full dialog by default.
    expand_save_panel: true
    expand_print_panel: true

