---
- name: Install system packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  when: "ansible_os_family == Debian"
  tags: [become]
  with_items:
    - build-essential
    - byobu
    - ca-certificates # Set of certificates from Certificate Authorities.
    - ccache # Speed up gcc/g++ functionality.
    - cmake
    - curl
    - file
    - gcc
    - git
    - gnupg2 # OpenPGP implementation.
    - g++
    - htop
    - httpie # Command-line HTTP client.
    - jq # Command-line JSON processor.
    - locales
    - libffi-dev # SNI Support.
    - libmysqlclient-dev
    - libssl-dev # SNI Support.
    - make
    - man
    - moreutils # For sponge.
    - mysql-client-8.0
    - ndg-httpsclient
    - nodejs
    - npm
    - pkg-config
    - pv # Progress viewer.
    - pyasn1
    - pyopenssl
    - python3
    - python3-dev
    - python3-pip
    - python3-setuptools
    - sed
    - software-properties-common
    - unzip
    - vim
    - xz-utils
    - wget

- name: Upgrade system packages
  ansible.builtin.apt:
    autoremove: true
    upgrade: dist
    update_cache: true
  become: true
  when: ansible_os_family == "Debian"
  tags: [become]

- name: Update ccache symlinks
  ansible.builtin.command: /usr/sbin/update-ccache-symlinks
  become: true
  changed_when: false
  tags: [become]

- name: Update locale
  ansible.builtin.command: locale-gen en_US.UTF-8 && update-locale LANG=en_US.UTF-8
  become: true
  changed_when: false
  tags: [become]
