---
# https://github.com/geerlingguy/ansible-collection-mac/blob/master/roles/homebrew/

homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
homebrew_folders_base:
  - Cellar
  - Homebrew
  - Frameworks
  - Caskroom
  - bin
  - etc
  - include
  - lib
  - opt
  - sbin
  - share
  - share/man
  - share/man/man1
  - share/man/man2
  - share/man/man3
  - share/man/man4
  - share/man/man5
  - share/man/man6
  - share/man/man7
  - share/man/man8
  - share/zsh
  - share/zsh/site-functions
  - var
