---
# https://github.com/geerlingguy/ansible-collection-mac/blob/master/roles/homebrew/

homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
homebrew_folders_base:
  - Cellar
  - Homebrew
  - Frameworks
  - Caskroom
  - bin
  - etc
  - include
  - lib
  - opt
  - sbin
  - share
  - share/zsh
  - share/zsh/site-functions
  - var
