---
- name: Run macos homebrew role
  ansible.builtin.include_role:
    name: macos_homebrew
  when: ansible_os_family == "Darwin"

- name: Run macos mas role
  ansible.builtin.include_role:
    name: macos_mas
  when: ansible_os_family == "Darwin"

- name: Run macos osx defaults role
  ansible.builtin.include_role:
    name: macos_osx_defaults
  when: ansible_os_family == "Darwin"

- name: Run macos power role
  ansible.builtin.include_role:
    name: macos_power
  when: ansible_os_family == "Darwin"

- name: Run macos misc role
  ansible.builtin.include_role:
    name: macos_misc
  when: ansible_os_family == "Darwin"
