---
- name: Run all homebrew install role
  ansible.builtin.include_role:
    name: all_homebrew_install
  tags: [become]

- name: Run all homebrew role
  ansible.builtin.include_role:
    name: all_homebrew

- name: Run all nodejs role
  ansible.builtin.include_role:
    name: all_nodejs

- name: Run all pipx role
  ansible.builtin.include_role:
    name: all_pipx

- name: Run all pre-commit role
  ansible.builtin.include_role:
    name: all_pre_commit

- name: Run all ruby role
  ansible.builtin.include_role:
    name: all_ruby
