---
  - name: Run all homebrew role.
    include_role:
      name: all-homebrew
    tags: ['homebrew', 'always']  # Enable skipping using always tag – for testing on travis.

  # FIXME: Why broken?
  # - name: Run all macos role.
  #   include_role:
  #     name: all.macos
  #   tags: ['macos']

  - name: Run all macdock role after homebrew role.
    include_role:
      name: all-macdock
    tags: ['macdock', 'always']

  - name: Run all mas role.
    include_role:
      name: all-mas
    tags: ['mas']

  - name: Run all macos-standby role.
    include_role:
      name: all-macos-standby
    tags: ['macos-standby']

  - name: Run all osx-defaults role.
    include_role:
      name: all-osx-defaults
    tags: ['osx-defaults']
