---

# FIXME:
#- name: Run all homebrew role.
#  include_role:
#    name: all-homebrew
#  tags: ['always']  # Always run, even when tags specified.
#
#- name: Run all nodejs role.
#  include_role:
#    name: all-nodejs
#  tags: ['always']  # Always run, even when tags specified.
#
    - name: Run all pipx role.
      include_role:
          name: all-pipx
      tags: [always] # Always run, even when tags specified.

# FIXME:
#- name: Run all ruby role.
#  include_role:
#    name: all-ruby
#  tags: ['always']  # Always run, even when tags specified.
#
#- name: Run personal homebrew role.
#  include_role:
#    name: personal-homebrew
#  tags: ['never', 'personal']  # This won't run unless you specify the 'personal' tag.
#
#- name: Run work homebrew role.
#  include_role:
#    name: work-homebrew
#  tags: ['never', 'work']  # This won't run unless you specify the 'work' tag.
