---
#- name: Run all homebrew role.
#  include_role:
#    name: all-homebrew
#  tags: ['homebrew', 'skip-travis']  # Enable skipping using skip-travis tag – for testing on travis.

#- name: Run all macdock role after homebrew role.
#  include_role:
#    name: all-macdock
#  tags: ['macdock', 'skip-travis']

- name: Run all macos role.
  include_role:
    name: all-macos
  tags: ['macos']

- name: Run all macos-standby role.
  include_role:
    name: all-macos-standby
  tags: ['macos-standby']
  # An alternative is appian.macos-power.

#- name: Run all mas role.
#  include_role:
#    name: all-mas
#  tags: ['mas', 'skip-travis']

#- name: Run all nodejs role.
#  include_role:
#    name: all-nodejs
#  tags: ['nodejs', 'skip-travis']

#- name: Run all osx-defaults role.
#  include_role:
#    name: all-osx-defaults
#  tags: ['osx-defaults']

- name: Run all osx_defaults role.
  include_role:
    name: all-osx_defaults
  tags: ['osx-defaults', 'skip-travis']

#- name: Run all pipx role.
#  include_role:
#    name: all-pipx
#  tags: ['pipx', 'skip-travis']

#- name: Run all ruby role.
#  include_role:
#    name: all-ruby
#  tags: ['ruby', 'skip-travis']
