---
- name: Check for login shell
  ansible.builtin.command: grep '^{{ item }}$' /etc/shells
  register: osx_login_shell_exists_in_etc_shells
  changed_when: false
  failed_when: osx_login_shell_exists_in_etc_shells.rc not in [0, 1]

- name: Add login shell if missing
  ansible.builtin.lineinfile:
    dest: /etc/shells
    line: "{{ item }}"
    state: present
    owner: root
    group: wheel
    mode: 0644
  when: osx_login_shell_exists_in_etc_shells.rc == 1

- name: Change user shell if necessary
  ansible.builtin.command: chsh -s {{ item }}
  register: user_shell
  changed_when: user_shell.stderr.find('no changes made') > 0
  become: true
  tags: [become]
