---
- name: Upgrade all homebrew packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  changed_when: false
  tags: [always]

- name: Upgrade all casks
  community.general.homebrew_cask:
    greedy: true
    upgrade_all: true
  changed_when: false # Greedy packages will get updated regardless, I think.
  tags: [always]

- name: Cleanup homebrew
  ansible.builtin.command: brew cleanup
  changed_when: false
  tags: [always]
# args:
#   warn: false  # set warn=false to prevent warning

- name: Ensure arm64 homebrew bash is an authorized shell
  ansible.builtin.include_tasks: login_shell.yml
  with_items:
    - /opt/homebrew/bin/bash
  when: ansible_machine == 'arm64'
  tags: [always]

- name: Ensure amd64 homebrew bash is an authorized shell
  ansible.builtin.include_tasks: login_shell.yml
  with_items:
    - /usr/local/bin/bash
  when: ansible_machine != 'arm64'
  tags: [always]
