---
AppStore_Enabled: true                           # Enable AppStore configuration
AppStore_AutomaticCheckEnabled: true             # Automatically check for updates
AppStore_AutomaticDownload: true                 # Download newly available updates in the background
AppStore_AutoUpdate: true                        # Install app updates
AppStore_AutoUpdateRestartRequired: true         # Install OSX updates
AppStore_ConfigDataInstall: true                 # Install system data files (XProtect and Gatekeeper)
AppStore_CriticalUpdateInstall: true             # Install security updates
AppStore_ScheduleFrequency: 1                    # Check for software updates (in days)
AppStore_ShowDebugMenu: true                     # Show debug menu

Bluetooth_Enabled: true                          # Enable Bluetooth configuration
Bluetooth_ShowInMenuBar: true                    # Show Bluetooth in menu bar

Dashboard_Enabled: true                          # Enable Dashboard configuration
Dashboard_McxDisabled: true                      # Disable Dashboard
Dashboard_EnabledState: 1                        # Dashboard state (1: Off, 2: As Space, 3: As Overlay)
Dashboard_DontShowAsSpace: true                  # Don’t show Dashboard as a Space
Dashboard_DevMode: false                         # Enable Dashboard dev mode (allows keeping widgets on the desktop)

DateTime_Enabled: true                           # Enable Date Time configuration
DateTime_TimeZone: "America/New_York"            # Set the timezone; see `systemsetup -listtimezones` for other values
DateTime_AutomaticDateTime: "on"                 # Set date and time automatically (on | off)
DateTime_TimeServer: "time.apple.com"            # Set time server
DateTime_AutomaticTimeZone: true                 # Set time zome automatically using current location
# Menu bar clock format - "h:mm": Default, "HH": Use a 24-hour clock
# "a": Show AM/PM, "ss": Display the time with seconds
DateTime_DateFormat: "HH:mm:ss"
DateTime_FlashDateSeparators: false              # Flash the time separators
DateTime_IsAnalog: false                         # Analog menu bar clock

DesktopScreenSaver_Enabled: false                # Enable Desktop and Screen Saver configuration
DesktopScreenSaver_BackGroundImage: ""           # Background iamge
# /Users/eric/src/github/lafarer/osx-ansible-config/images/toy-story-02.jpg

Displays_Enabled: true                           # Enable Displays configuration
Displays_AutomaticallyAdjustBrightness: true     # Automatically adjust brightness
Displays_ShowInMenuBarIfPresent: true            # Show mirroring options in the menu bar when available
# Subpixel font rendering on non-Apple LCDs (0:Disabled, 1:Minimal, 2:Medium, 3:Smoother, 4:Strong)
Displays_AppleFontSmoothing: 2
Displays_DisplayResolutionEnabled: true          # Enable HiDPI display modes (requires restart)

Dock_Enabled: true                               # Enable Dock configuration
Dock_TileSize: 64                                # Dock size
Dock_Magnification: true                         # Dock magnification
Dock_LargeSize: 128                              # Icon size of magnified Dock items
Dock_Orientation: "bottom"                       # Dock orientation: left, bottom, right
Dock_MinEffect: "scale"                          # Minimization effect: genie, scale, suck
Dock_AppleActionOnDoubleClick: "Maximize"        # Double-click a window's title title bar to: None, Minimize, Maximize
Dock_MinimizeToApplication: false                # Minimize windows appliction into icon (true, false)
Dock_LaunchAnim: true                            # Animate opening applications
Dock_Autohide: true                              # Automatically hide and show the Dock
Dock_ShowProcessIndicators: true                 # Show indicator for open applications
Dock_ShowHidden: false                           # Display translucent Dock icons for hidden applications

Finder_Enabled: true                             # Enable Finder configuration
Finder_ShowHardDrivesOnDesktop: true             # Show hard drives on the desktop
Finder_ShowExternalHardDrivesOnDesktop: true     # Show external hard drives on the desktop
Finder_ShowRemovableMediaOnDesktop: true         # Show CDs,DVDs and iPods on the desktop
Finder_ShowMountedServersOnDesktop: true         # Show connected servers on the desktop
# New Finder windows shows - PfCm:Computer, PfVo:Computer's HD, PfHm:Home, PfDe:Desktop,
# PfDo:Documents, PfAF:All My files
Finder_NewWindowTarget: "PfDe"
Finder_FinderSpawnTab: true                      # Open folders in tabs instead of new windows
Finder_AppleShowAllExtensions: true              # Show all fiename extensions
Finder_FXEnableExtensionChangeWarning: true      # Show warning before changing an extension
Finder_WarnOnEmptyTrash: true                    # Show warning before emptying the trash
# When performing a search - SCev:Search This Mac, SCcf:Search the Current Folder
# SCsp:Use the Previous Search Scope
Finder_FXDefaultSearchScope: "SCev"
Finder_AppleShowAllFiles: true                   # Show hidden files
# View as (icnv:Icons, Nlsv:List, clmv:Column, Flwv:Cover Flow)
Finder_FXPreferredViewStyle: "clmv"
# Arrange By (None, Name, Application Category, Date Last Opened, Date Added, Size, Finder Tags)
Finder_FXPreferredGroupBy: "None"
Finder_ShowTabView: true                         # Show Tab Bar
Finder_ShowPathbar: true                         # Show Path Bar
Finder_ShowStatusBar: true                       # Show Status Bar
Finder_ShowSidebar: true                         # Show Side Bar
Finder_ColumnShowIcons: true                     # Show Preview
Finder_FXShowPosixPathInTitle: true              # Show full POSIX path as Finder window title

General_Enabled: true                            # Enable General configuration
General_AppleAquaColorVariant: 1                 # Set appearance (1: Blue, 6: Graphite)
General_AppleInterfaceStyle: ""                  # Use Dark menu bar and Dock (Empty or "Dark")
General_AutoHideMenuBar: false                   # Automatically hide and show the menu bar
# Highlight color (Red, Orange, Yellow, Green, Blue, Purple, Pink, Brown, Graphite)
General_AppleHighlightColor: "Blue"
General_SidebarIconSize: 1                       # Sidebar icon size (Small: 1, Medium: 2, Large: 3)
# Scroll bar visibility (WhenScrolling, Automatic, Always)
General_AppleShowScrollBars: "Always   "
# Click in the scrollbar to (0: Jump to the next page, 1: Jump to the spot that's clicked)
General_AppleScrollerPagingBehavior: 0
General_NSCloseAlwaysConfirmsChanges: true       # Ask to keep changes when closing documents
General_CloseWindowsWhenQuittingApp: false       # Close windows when quitting an application
General_NSScrollAnimationEnabled: true           # Smooth scrolling (Disable on older Macs)

ICloud_Enabled: false                            # Enable iCloud configuration
ICloud_NSDocumentSaveNewDocumentsToCloud: true   # Save to iCloud by default

Keyboard_Enabled: true                             # Enable Keyboard configuration
Keyboard_KeyRepeat: 0                              # Set key repeat rate (Off: 300000, Slow: 120, Fast: 2)
Keyboard_InitialKeyRepeat: 10                      # Set delay until repeat, in milliseconds (Long: 120, Short: 15)
Keyboard_fnState: false                            # Use F1, F2, etc. keys as standard function keys
Keyboard_kDim: true                                # Adjust keyboard brightness in low light
# Dim keyboard after idle time (in seconds, 0 is Never)
Keyboard_kDimTime: 60
Keyboard_AutomaticSpellingCorrectionEnabled: false  # Correct spelling automatically
Keyboard_AutomaticQuoteSubstitutionEnabled: false  # Use smart quotes
Keyboard_AutomaticDashSubstitutionEnabled: false   # Use smart dashes
# Full Keyboard Access (1 : Text boxes and lists only, 3 : All controls)
Keyboard_AppleKeyboardUIMode: 3
# Prevent accidental Power button presses from sleeping system
Keyboard_PowerButtonSleepsSystem: false
# Disable press-and-hold for keys in favor of key repeat
Keyboard_PressAndHoldEnabled: false

LanguageRegion_Enabled: true                     # Enable Language and Region configuration
# FIXME: https://github.com/ansible/ansible-modules-extras/issues/2610
# FIXME: https://github.com/ansible/ansible/issues/19585
# Preferred languages (in order of preference e.g. [ "en", "fr" ])
# LanguageRegion_Languages: [ "en", "fr" ]
# Locale and Currency (United States : en_US@currency=USD, Great Britian : en_GB@currency=EUR)
LanguageRegion_Locale: "en_US@currency=USD"
LanguageRegion_MeasurementUnits: "Inches"        # Measure Units (Inches, Centimeters)
LanguageRegion_Force24HourTime: "true"           # Force 12/24 hour time
LanguageRegion_MetricUnits: "false"              # Set Metric Units

MissionControl_Enabled: true                     # Enable Mission Control configuration
# Automatically rearrange Spaces based on most recent use
MissionControl_MruSpaces: false
# When switching to an application, switch to a Space with open windows for the application
MissionControl_SwitchOnActivate: true
MissionControl_GroupByApp: true                  # Group windows by application in Mission Control
MissionControl_SpansDisplays: true               # Displays have separate Spaces

Safari_Enabled: true                             # Enable Safari configuration
# General - Safari opens with ("A new window", "A new private window",
# "All windows from last session")
Safari_OpensWith: "All windows from last session"
# General - New windows open with (0:Hompage, 1:Empty page, 2:Same page, 4:Favorites
# 5:Tabs for Favorites)
Safari_NewWindowBehavior: 1
# General - New tabs open with (0:Hompage, 1:Empty page, 2:Same page, 4:Favorites)
Safari_NewTabBehavior: 41
# General - Remove history items after (number of days - 1:One day, 7:One week, 14:Two weeks,
# 31:One month, 365:One year)
Safari_HistoryAgeInDaysLimit: 365
# General - Top Sites shows (0:6 sites, 1:12 sites, 2:24 sites)
Safari_TopSitesGridArrangement: 1
# General - Remove download list items (0:Manually, 1:After one day,
# 2:Upon successfull download, 3:When Safari quits)
Safari_DownloadsClearingPolicy: 3
Safari_AutoOpenSafeDownloads: false              # General - Open 'safe' files after downloading
# Tabs - Open pages in tabs instead of windows (0:Never, 1:Automatically, 2:Always)
Safari_TabCreationPolicy: 1
Safari_CommandClickMakesTabs: true               # Tabs - cmd+click opens a link in a new tab
# Tabs - When a new tab or window opens, make it active
Safari_OpenNewTabsInFront: false
Safari_Command1Through9SwitchesTabs: true        # Tabs - Use cmd+1 through cmd+9 to switch tabs
Safari_AutoFillFromAddressBook: true             # Autofill - Using info from my Contact card
Safari_AutoFillPasswords: true                   # Autofill - Using names and passwords
Safari_AutoFillCreditCardData: false             # Autofill - Using Credit cards
Safari_AutoFillMiscellaneousForms: true          # Autofill - Using Other forms
# Search - Search engine (Google, Yahoo, Bing, DuckDuckGo)
Safari_SearchEngine: "Google"
Safari_IncludeSearchSuggestions: true            # Search - Include search engine suggestions
# Search - Smart Search Field - Enable Quick Website Search
Safari_WebsiteSpecificSearchEnabled: true
# Search - Smart Search Field - Preload Top Hit in the background
Safari_PreloadTopHit: true
Safari_ShowFavoritesUnderSmartSearchField: true  # Search - Smart Search Field - Show Favorites
# Security - Fraudulent Sites - Warn when visiting a fraudulent website
Safari_WarnAboutFraudulentWebsites: true
Safari_JavaScriptEnabled: true                   # Security - Web Content - Enable Javascript
Safari_BlockPopupWindows: true                   # Security - Web Content - Block pop-up windows
Safari_AllowWebGL: true                          # Security - Web Content - Allow WebGL
Safari_AllowPlugins: true                        # Security - Internet plug-ins - Allow Plug-ins
# Privacy - Cookies and website data ("Always block", "Always from current website only",
# "Allow from websites I visit", "Always allow")
Safari_Cookies: "Always from current website only"
# Privacy - Website use of location services (0:Deny without prompting,
# 1:Prompt for each site once each day, 2:Prompt for each site one time only)
Safari_SafariGeolocationPermissionPolicy: 2
# Privacy - Website tracking - Ask websites not to track me
Safari_SendDoNotTrackHTTPHeader: true
# Notification - Allow websites to ask for permission to send push notifications
Safari_CanPromptForPushNotifications: true
# Exensions - Automatically update extensions from Safari Extensions Gallery
Safari_InstallExtensionUpdatesAutomatically: true
# Advanced - Smart Search Field - Show full website address
Safari_ShowFullURLInSmartSearchField: false
# Advanced - Accessibility - Never use font sizes smaller than (0 means disabled)
Safari_WebKitMinimumFontSize: 0
# Advanced - Accessibility - Press Tab to highlight ach item on a webpage
Safari_WebKitTabToLinksPreferenceKey: false
# Advanced - Bonjour - Include Bonjour in the Bookmarks Menu
Safari_BookmarksMenuIncludesRendezvous: false
# Advanced - Internet plug-ins - Stop plug-ins to saver power
Safari_StopPuginsToSavePower: true
Safari_ShowDeloperMenu: true                     # Advanced - Show Develop menu in menu bar
Safari_ShowFavoritesBar: true                    # View - Show Favorites Bar
Safari_AlwaysShowTabBar: true                    # View - Show Tab Bar
Safari_ShowOverlayStatusBar: true                # View - Show Status Bar
Safari_ShowSidebarInNewWindows: true             # View - Show Sidebar
# View - Show Sidebar Mode ("Bookmarks","Reading List","Social Links")
Safari_SidebarViewModeIdentifier: "Bookmarks"
Safari_ShowFrequentlyVisitedSites: true          # Bookmarks - Show Frequently Visited in Favorites
