---
- name: Show the main window when launching Activity Monitor
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: OpenMainWindow
    type: bool
    value: true
    state: present
  tags: [always]

- name: Visualize CPU usage in the Activity Monitor Dock icon
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: IconType
    type: int
    value: 5
    state: present
  tags: [always]

- name: Show all processes in Activity Monitor
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: ShowCategory
    type: int
    value: 0
    state: present
  tags: [always]

- name: Sort Activity Monitor results by CPU usage
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: SortColumn
    type: string
    value: CPUUsage
    state: present
  tags: [always]

- name: Sort Activity Monitor results by CPU usage
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: SortDirection
    type: int
    value: 0
    state: present
  tags: [always]
