---
- name: Caffeine - Activate on launch
  community.general.osx_defaults:
    domain: com.lightheadsw.caffeine
    key: ActivateOnLaunch
    type: bool
    value: false
    state: present
  notify: Restart Caffeine
  tags: [always]

- name: Caffeine - Suppress launch message
  community.general.osx_defaults:
    domain: com.lightheadsw.caffeine
    key: SuppressLaunchMessage
    type: bool
    value: true
    state: present
  notify: Restart Caffeine
  tags: [always]

- name: Caffeine - Set duration to infinity
  community.general.osx_defaults:
    domain: com.lightheadsw.caffeine
    key: DefaultDuration
    type: string
    value: '0'
    state: present
  notify: Restart Caffeine
  tags: [always]
