---
- name: Dock - Turn off bouncing icons
  community.general.osx_defaults:
    domain: com.apple.dock
    key: no-bouncing
    type: bool
    value: true
    state: present
  notify: Restart Dock
  tags: [always]

- name: Dock - Change minimize/maximize window effect
  community.general.osx_defaults:
    domain: com.apple.dock
    key: mineffect
    type: string
    value: scale
    state: present
  notify: Restart Dock
  tags: [always]

- name: Dock - Move to bottom middle of the screen
  community.general.osx_defaults:
    domain: com.apple.dock
    key: pinning
    type: string
    value: middle # Other options: "start", "end".
    state: present
  notify: Restart Dock
  tags: [always]

- name: Dock - Move to bottom middle of the screen
  community.general.osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: bottom # Other options: "left", "right".
    state: present
  notify: Restart Dock
  tags: [always]

- name: Dock - Enable spring loading for all items
  community.general.osx_defaults:
    domain: com.apple.dock
    key: enable-spring-load-actions-on-all-items
    type: bool
    value: true
    state: present
  notify: Restart Dock
  tags: [always]

- name: Dock - Speeding up Mission Control animations and grouping windows by application
  community.general.osx_defaults:
    domain: com.apple.dock
    key: expose-animation-duration
    type: float
    value: 0.1
    state: present
  notify: Restart Dock
  tags: [always]

- name: Dock - Misson Control group by application
  community.general.osx_defaults:
    domain: com.apple.dock
    key: expose-group-by-app
    type: bool
    value: true
    state: present
  notify: Restart Dock
  tags: [always]

- name: Dock - Enabling iTunes track notifications
  community.general.osx_defaults:
    domain: com.apple.dock
    key: itunes-notifications
    type: bool
    value: true
    state: present
  notify: Restart Dock
  tags: [always]

- name: Dock - Don't animate opening applications
  community.general.osx_defaults:
    domain: com.apple.dock
    key: launchanim
    type: bool
    value: false
    state: present
  notify: Restart Dock
  tags: [always]

- name: Dock - Don't show Dashboard as a Space
  community.general.osx_defaults:
    domain: com.apple.dock
    key: dashboard-in-overlay
    type: bool
    value: true
    state: present
  notify: Restart Dock
  tags: [always]

- name: Dock - Set springboard rows
  community.general.osx_defaults:
    domain: com.apple.dock
    key: springboard-rows
    type: int
    value: 8
    state: present
  notify: Restart Dock
  tags: [always]

- name: Dock - Set springboard columns
  community.general.osx_defaults:
    domain: com.apple.dock
    key: springboard-columns
    type: int
    value: 8
    state: present
  notify: Restart Dock
  tags: [always]

- name: Dock - Making launchpad better
  community.general.osx_defaults:
    domain: com.apple.dock
    key: ResetLaunchPad
    type: bool
    value: true
    state: present
  notify: Restart Dock
  tags: [always]

# Hot corners
# Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center

- name: Dock - Top left screen corner → Disable screen saver
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-tl-corner
    type: int
    value: 6
    state: present
  notify: Restart Dock
  tags: [always]

- name: Dock - Top left screen corner → Disable screen saver
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-tl-modifier
    type: int
    value: 0
    state: present
  notify: Restart Dock
  tags: [always]

- name: Dock - Bottom right screen corner → Start screen saver
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-br-corner
    type: int
    value: 5
    state: present
  notify: Restart Dock
  tags: [always]

- name: Dock - Bottom right screen corner → Start screen saver
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-br-modifier
    type: int
    value: 0
    state: present
  notify: Restart Dock
  tags: [always]

- name: Dock - Make animation snappier
  community.general.osx_defaults:
    domain: com.apple.dock
    key: workspaces-edge-delay
    type: float
    value: 0.1
    state: present
  notify: Restart Dock
  tags: [always]

- name: Dock - Set dock tilesize
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: 50
  notify: Restart Dock
  tags: [always]

- name: Dock - Show indicator lights for open applications in the dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: show-process-indicators
    type: bool
    value: true
  notify: Restart Dock
  tags: [always]

- name: Dock - Make dock icons of hidden applications translucent
  community.general.osx_defaults:
    domain: com.apple.dock
    key: showhidden
    type: bool
    value: true
  notify: Restart Dock
  tags: [always]

- name: Dock - Rearrange spaces by last use
  community.general.osx_defaults:
    domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: true
  notify: Restart Dock
  tags: [always]

- name: Dock - Set dock fade-in time
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0
  notify: Restart Dock
  tags: [always]

- name: Dock - Automatically hide
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
  notify: Restart Dock
  tags: [always]

- name: Dock - Removing the auto-hiding time modifier
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-time-modifier
    type: float
    value: 0
    state: present
  notify: Restart Dock
  tags: [always]
