---
- name: Flux - Set flag that app has launched before
  community.general.osx_defaults:
    domain: org.herf.Flux.plist
    key: SUHasLaunchedBefore
    type: bool
    value: true
    state: present
  notify: Restart Flux
  tags: [always]

- name: Flux - Enable automatic update checks
  community.general.osx_defaults:
    domain: org.herf.Flux.plist
    key: SUEnableAutomaticChecks
    type: bool
    value: true
    state: present
  notify: Restart Flux
  tags: [always]

- name: Flux - Set location
  community.general.osx_defaults:
    domain: org.herf.Flux.plist
    key: location
    type: string
    value: "42.5,-71.2"
    state: present
  notify: Restart Flux
  tags: [always]

- name: Flux - Set locationTextField
  community.general.osx_defaults:
    domain: org.herf.Flux.plist
    key: locationTextField
    type: string
    value: "02474"
    state: present
  notify: Restart Flux
  tags: [always]

- name: Flux - Set late night colour temperature
  community.general.osx_defaults:
    domain: org.herf.Flux.plist
    key: lateColorTemp
    type: int
    value: 3400
    state: present
  notify: Restart Flux
  tags: [always]

- name: Flux - Set night colour temperature
  community.general.osx_defaults:
    domain: org.herf.Flux.plist
    key: nightColorTemp
    type: int
    value: 1900
    state: present
  notify: Restart Flux
  tags: [always]
