---
- name: iTerm2 - Enable automatic updates
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: SUEnableAutomaticChecks
    type: bool
    value: true
  notify: Restart iTerm2

- name: iTerm2 - Set custom preferences folder
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    type: string
    value: $HOME/.config/iterm2
  when: iterm2_preference_folder is defined
  notify: Restart iTerm2

- name: iTerm2 - Enable custom preferences folder
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: LoadPrefsFromCustomFolder
    type: bool
    value: true
  when: iterm2_preference_folder is defined
  notify: Restart iTerm2

# See: https://security.stackexchange.com/a/47786/8918
- name: iTerm2 - Disable Secure Keyboard Entry
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: Secure Input
    type: bool
    value: false
  notify: Restart iTerm2
