---
- name: Login Window - Reveal IP address, hostname, OS version, etc. when clicking the clock
  community.general.osx_defaults:
    domain: com.apple.loginwindow
    key: AdminHostInfo
    type: string
    value: HostName
    state: present
  tags: [always]
