---
- name: Menu Extra - Use 24-hour format
  community.general.osx_defaults:
    domain: com.apple.menuextra.clock
    key: DateFormat
    type: string
    value: EEE HH:mm # Other values, e.g., "EEE MMM d  h:mm a".
    state: present

- name: Menu Extra - Show battery percentage
  community.general.osx_defaults:
    domain: com.apple.menuextra.battery
    key: ShowPercent
    type: string
    value: YES # yamllint disable-line rule:truthy
    state: present
