---
- name: Trackpad – enable click and drag
  community.general.osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: Dragging
    type: int
    value: 1
    state: present
  tags: [always]

- name: Trackpad - enable click and drag for bluetooth trackpads
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Dragging
    type: int
    value: 1
    state: present
  tags: [always]

- name: System Preferences – Organize Alphabetically
  community.general.osx_defaults:
    domain: com.apple.systempreferences
    key: ShowAllMode
    type: bool
    value: true
    state: present
  tags: [always]

- name: System Sound –Disable UI sounds
  community.general.osx_defaults:
    domain: com.apple.systemsound
    key: com.apple.sound.uiaudio.enabled
    type: int
    value: 0
    state: present
  tags: [always]

- name: Bluetooth – Increase sound quality for headphones/headsets
  community.general.osx_defaults:
    domain: com.apple.BluetoothAudioAgent
    key: Apple Bitpool Min (editable)
    type: int
    value: 40
    state: present
  tags: [always]

- name: IOKit - Enable display from automatically adjusting brightness
  community.general.osx_defaults:
    domain: com.apple.iokit.AmbientLightSensor
    key: Automatic Display Enabled
    type: bool
    value: true
    state: present
  tags: [always]

- name: IOKit - Disable keyboard from automatically adjusting backlight brightness in low light
  community.general.osx_defaults:
    domain: com.apple.iokit.AmbientLightSensor
    key: Automatic Keyboard Enabled
    type: bool
    value: false
    state: present
  tags: [always]

- name: Network Browser - Enable AirDrop over Ethernet and on Unsupported Macs
  community.general.osx_defaults:
    domain: com.apple.NetworkBrowser
    key: BrowseAllInterfaces
    type: bool
    value: true
    state: present
  tags: [always]

- name: Network Connect –Show Time Connected to VPN
  community.general.osx_defaults:
    domain: com.apple.networkConnect
    key: VPNShowTime
    type: int
    value: 1
    state: present
  tags: [always]

- name: Captive - Disable the built-in portal (use your browser instead)
  community.general.osx_defaults:
    domain: com.apple.captive.control
    key: Active
    type: bool
    value: false
    state: present
  tags: [always]

- name: Dashboard - Disable
  community.general.osx_defaults:
    domain: com.apple.dashboard
    key: mcx-disabled
    type: bool
    value: true
  tags: [always]

- name: Desktop Services - Disable creating .DS_Store files on network shares
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
  tags: [always]

- name: Desktop Services - Disable creating .DS_Store files on usb drives
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: true
  tags: [always]

- name: Disk Images - Disable verification
  community.general.osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: '{{ item }}'
    type: bool
    value: true
  with_items:
    - skip-verify
    - skip-verify-locked
    - skip-verify-remote
  tags: [always]

- name: CrashReporter - Enable
  community.general.osx_defaults:
    domain: com.apple.CrashReporter
    state: absent
    key: DialogType
    type: string
    value: falsene
  tags: [always]

- name: Spotlight - Disable indexing network volumes
  become: true
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.SpotlightServer.plist
    key: ExternalVolumesIgnore
    type: bool
    value: true
  tags: [become]
