---
- name: Trackpad –Set speed to a reasonable number
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.trackpad.scaling
    type: int
    value: 2
    state: present
  tags: [always]

- name: Mouse - Setting speed to a reasonable number
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.scaling
    type: float
    value: 2.5
    state: present
  tags: [always]

- name: Trackpad - enable tap to click for this user and for the login screen
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    type: bool
    value: true
    state: present
  tags: [always]

- name: Sound - Disable beeps on level change
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.sound.beep.feedback
    type: int
    value: 0
    state: present
  tags: [always]

- name: Set language and text formats
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleLanguages
    type: array
    value:
      - en
    state: present
  tags: [always]

- name: Set currency formats
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleLocale
    type: string
    value: en_US@currency=USD
    state: present
  tags: [always]

- name: Set measurement formats
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleMeasurementUnits
    type: string
    value: Inches
    state: present
  tags: [always]

- name: Set unit formats
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleMetricUnits
    type: bool
    value: false
    state: present
  tags: [always]

- name: Use 24-hour format
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleICUForce24HourTime
    type: bool
    value: true
    state: present
  tags: [always]

- name: Use Monday as the first day of the week
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleFirstWeekday
    type: string
    value: "{gregorian = 2;}"
    state: present
  tags: [always]

- name: Show fast user switching menu as [Icon]
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: userMenuExtraStyle
    type: int
    value: 2
    state: present
  tags: [always]

- name: Displaying ASCII control characters using caret notation in standard text views
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSTextShowsControlCharacters
    type: bool
    value: true
    state: present
  tags: [always]

- name: Set sidebar icon size to 'medium'
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSTableViewDefaultSizeMode
    type: int
    value: 2
    state: present
  tags: [always]

- name: Add a context menu item for showing the Web Inspector in web views
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: WebKitDeveloperExtras
    type: bool
    value: true
    state: present
  tags: [always]

- name: UI - Expand save panel by default
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true
  notify: Restart Finder
  tags: [always]

- name: UI - Expand print panel by default
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint
    type: bool
    value: true
  notify: Restart Finder
  tags: [always]

- name: Springing - Enable spring loading for directories
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.springing.enabled
    type: bool
    value: true
  tags: [always]

- name: Springing - Set delay for spring loading directories
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.springing.delay
    type: float
    value: 2
  tags: [always]

- name: UI - Set action for double click on titlebar
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleActionOnDoubleClick
    type: string
    value: Maximize # "Maximize", "Minimize".
  tags: [always]

- name: UI - Set interface style
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleInterfaceStyle
    type: string
    value: Dark # "Light", "Dark".
  tags: [always]

- name: UI - Enable subpixel font rendering on non-Apple LCDs
  community.general.osx_defaults:
    domain: NSGlobalDomain
    state: present
    key: AppleFontSmoothing
    type: int
    value: 1
  tags: [always]

- name: UI - Show all file extensions
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
  tags: [always]

- name: UI - Enable focus ring
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSUseAnimatedFocusRing
    type: bool
    value: false
  tags: [always]

- name: UI - Enable menubar transparency
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleEnableMenuBarTransparency
    type: bool
    value: true
  tags: [always]

- name: UI - Show scrollbars
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowScrollBars
    type: string
    value: WhenScrolling # Values: "WhenScrolling", "Always".
  tags: [always]

- name: UI - Enable opening and closing window animations
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticWindowAnimationsEnabled
    type: bool
    value: true
  tags: [always]

- name: UI - Set window resize speed for Cocoa applications
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSWindowResizeTime
    type: float
    value: 0.2
  tags: [always]

- name: Input - Enable auto correct
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: true
  tags: [always]

- name: Input - Disable smart quotes
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false
  tags: [always]

- name: Input - Disable smart dashes
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false
  tags: [always]

- name: Input - Enable automatic capitalization
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: true
  tags: [always]

- name: Input - Enable automatic period substitution
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticPeriodSubstitutionEnabled
    type: bool
    value: true
  tags: [always]

- name: Input - Enable continuous spell checking
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAllowContinuousSpellChecking
    type: bool
    value: true
  tags: [always]

# 1 : Text boxes and lists only
# 3 : All controls
- name: Input - Enable full keyboard access for all controls
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleKeyboardUIMode
    type: int
    value: 3
  tags: [always]

- name: Input - Set key repeat rate
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 2
  tags: [always]

- name: Input - Set initial key repeat delay
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 22
  tags: [always]

- name: Input - Enable press-and-hold for special characters
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    type: bool
    value: true
  tags: [always]

- name: Misc - Save application state on quit
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSQuitAlwaysKeepsWindows
    type: bool
    value: true
  tags: [always]

- name: Misc - Save new docs to icloud by default
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: true
  tags: [always]
