---
- name: Photo Booth - Enable the debug menu
  community.general.osx_defaults:
    domain: com.apple.PhotoBooth
    key: EnableDebugMenu
    type: bool
    value: true
    state: present
  notify: Restart Photo Booth
  tags: [always]
