---
- name: Screensaver - Show with clock
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: showClock
    type: bool
    value: true
    state: present

- name: Screensaver - Set activation delay for screensaver
  community.general.osx_defaults:
    domain: com.apple.screensaver
    host: currentHost
    key: idleTime
    type: int
    value: 0

- name: Screensaver - Ask for a password when leaving the screensaver
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: 1

- name: Screensaver - Set ask password delay
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: float
    value: 0

- name: Screensaver - Set module name
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: moduleName
    type: string
    value: Aerial

- name: Screensaver - Set display name
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: displayName
    type: string
    value: Aerial

- name: Screensaver - Set path
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: path
    type: string
    value: "/Users/ftod/Library/Screen Savers/Aerial.saver"

- name: Screensaver - Set type
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: type
    type: int
    value: 0
