---
- name: Screen Capture - Save screenshots to the desktop
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: /Users/ftod/Desktop
    state: present

- name: Screen Capture - Save screenshots in PNG formats
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: type
    type: string
    value: png # other options: BMP, GIF, JPG, PDF, TIFF.
    state: present
