---
- name: Screen Sharing – Turn on Bonjour browser
  community.general.osx_defaults:
    domain: com.apple.ScreenSharing
    key: ShowBonjourBrowser_Debug
    type: bool
    value: true
    state: present
  notify: Restart Screen Sharing
