---
- name: Skype - Include debug menu
  community.general.osx_defaults:
    domain: com.skype.skype
    key: IncludeDebugMenu
    type: bool
    value: true
    state: present
  notify: Restart Skype
  tags: [always]

- name: Skype - Don't show welcome tour
  community.general.osx_defaults:
    domain: com.skype.skype
    key: SKShowWelcomeTour
    type: bool
    value: true
    state: present
  notify: Restart Skype
  tags: [always]

- name: Skype - Disable welcome tour
  community.general.osx_defaults:
    domain: com.skype.skype
    key: SKDisableWelcomeTour
    type: bool
    value: true
    state: present
  notify: Restart Skype
  tags: [always]

- name: Skype - Enable developer extras
  community.general.osx_defaults:
    domain: com.skype.skype
    key: WebKitDeveloperExtras
    type: bool
    value: true
    state: present
  notify: Restart Skype
  tags: [always]

- name: Skype - Don't disable developer extras
  community.general.osx_defaults:
    domain: com.skype.skype
    key: DisableWebKitDeveloperExtras
    type: bool
    value: true
    state: present
  notify: Restart Skype
  tags: [always]
