---
- name: Time Machine - Prevent prompting to use new hard drives as backup volume
  community.general.osx_defaults:
    domain: com.apple.TimeMachine
    key: DoNotOfferNewDisksForBackup
    type: bool
    value: true
    state: present
