---
- name: Xcode - Turn off welcome windows
  community.general.osx_defaults:
    domain: com.apple.dt.Xcode
    key: XCShowWelcomeWindow
    type: bool
    value: false
    state: present
  notify: Restart Xcode
