---
galaxy_info:
  author: Francis O'Donovan
  description: Generic homebrew role.
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - all
    - name: macOS
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags: []
dependencies:
  - role: geerlingguy.mac.homebrew
