---
- name: Check node is installed and upgraded
  community.general.homebrew:
    name: ["{{ item }}"]
    state: latest
  with_items:
    - node
  tags: [always]

- name: Install latest version of global nodejs packages
  community.general.npm:
    name: coffee-script
    global: true
    state: latest
  # ansible.builtin.command: npm install --global {{ item }}
  with_items: "{{ nodejs_global_packages }}"
  tags: [always]
