---
# https://github.com/geerlingguy/ansible-collection-mac/blob/master/roles/homebrew/tasks/main.yml
- name: Ensure configured taps are tapped
  community.general.homebrew_tap:
    tap: "{{ item.name | default(item) }}"
    url: "{{ item.url | default(omit) }}"
    state: present
  loop: "{{ homebrew_taps }}"
  tags: [always]

- name: Ensure blacklisted homebrew packages are not installed
  community.general.homebrew: "name={{ item }} state=absent"
  loop: "{{ homebrew_uninstalled_packages }}"
  tags: [always]

- name: Ensure configured homebrew packages are installed
  community.general.homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: "{{ item.state | default('latest') }}"
  loop: "{{ homebrew_installed_packages }}"
  tags: [always]

- name: Ensure work configured homebrew packages are installed
  community.general.homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: "{{ item.state | default('latest') }}"
  loop: "{{ work_homebrew_installed_packages }}"
  tags: # This won't run unless you specify the 'work' tag.
    - never
    - work
