---
- hosts: all

  roles:
    # FIXME: Put macos_power_settings in var file?
    - {role: appian.macos-power,
       become: yes,
       macos_power_settings: [
         {cmd: computersleep, desired_value: 'Never'},
         {cmd: displaysleep, desired_value: 'after 15 minutes'},
         {cmd: harddisksleep, desired_value: 'Never'},
         {cmd: restartfreeze, desired_value: 'Off'},
         {cmd: wakeonnetworkaccess, desired_value: 'On'},
       ]
    }
    - geerlingguy.nodejs
    - geerlingguy.pip
    - geerlingguy.ruby

  tasks:


# FIXME: Use roles and separate files to setup mac/ubuntu/centos machines.
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html
# Or maybe different things via ansible galaxy?
# See
# https://github.com/lafarer/ansible-role-osx-defaults/blob/18072c8e68afb2e2244825ad1a6f42affd75f1ed/tasks/main.yml

# FIXME: Can use same tag on multiple tasks to group tasks.

# FIXME: Can use prompts

# FIXME:
# ansible-role-pip
# ansible-role-dotfiles
# https://github.com/danbohea/ansible-role-rbenv
# https://github.com/fubarhouse/ansible-role-macdock
# https://github.com/danbohea/ansible-role-macos-dock
# https://galaxy.ansible.com/danbohea/flux - flux configuration?
# https://galaxy.ansible.com/shashikant86/ios-dev
# https://galaxy.ansible.com/drew-kun/macos_terminal
# https://galaxy.ansible.com/mhalano/dropbox
# https://galaxy.ansible.com/bjoernalbers/sysctl
#https://github.com/juju4/ansible-harden-darwin
#https://github.com/feffi/ansible-macos-softwareupdate
#https://github.com/dotstrap/ansible-xcode
#https://github.com/ansible/ansible-modules-extras/blob/devel/system/osx_defaults.py
#
#https://github.com/mego22/ansible-role-osx-settings
#https://github.com/lafarer/ansible-role-osx-jenv
#https://github.com/fubarhouse/ansible-role-macfonts
#https://github.com/0x4e3/osx-bootstrap-defaults
#https://github.com/osxstrap/ansible-osx-user-picture
#https://github.com/osxstrap/ansible-osx-software-update
#https://github.com/feffi/ansible-macos-git-repos
#https://github.com/feffi/ansible-macos-timemachine
#https://github.com/feffi/ansible-macos-standby
#https://github.com/openstack/ansible-hardening

# FIXME:
# https://stackoverflow.com/questions/25230376/how-to-automatically-install-ansible-galaxy-roles
# When creating galaxy requirements, specify hash so they are pinned!


# FIXME: Add pipx,
# FIXME: GT .bashrc .profile.
