---
# FIXME: Test just this host.
- hosts: ospideal.local
  vars:
    homebrew_installed_packages:
      - apache-spark
      - gbeine/homebrew-java/postgresql-jdbc
      - hadoop
      - homebrew/science/r
      - homebrew/versions/perl518
      - { name: mongodb, install_options: "with-openssl" }
      - mysql-connector-c
      - { name: octave, install_options: "with-gui" }
      - postgresql
      - scala
      - tomcat
    homebrew_cask_apps:
      - mendeley-desktop
      - mysqlworkbench
      - notebook
      - pycharm
      - sequel-pro
      - snowflake-snowsql
    roles:
      - homebrew

- hosts: firefly.local
  vars:
    homebrew_cask_apps:
      - backblaze
      - carmaintenance
      - google-backup-and-sync
      - google-photos-backup
      - handbrake
      - pycharm-ce
      - steam
      - subler
      - wireshark
    mas_installed_apps:
      - { id: 1055511498, name: "Day One" }
      - { id:  586862299, name: "Duplicate Cleaner For iPhoto" }
      - { id: 592704001, name: "Photos Duplicate Cleaner" }
    mas_signin_dialog: yes
    mas_upgrade_all_apps: yes
    roles:
      # - geerlingguy.mas  # FIXME: Broken on latest OSs.
      - homebrew

- hosts: all
  tasks:
    # - name: print facts
    #   debug:
    #     var: ansible_facts
    - include_role:
        name: darwin
      when: ansible_facts['os_family']|lower == 'darwin'
    - include_role:
        name: debian
      when: ansible_facts['os_family']|lower == 'debian'
    - include_role:
        name: redhat
      when: ansible_facts['os_family']|lower == 'redhat'
    - include_role:
        name: common

# FIXME: Cheatsheet installed via cask **and** mas?

# FIXME: Test using tags to limit what we use
#  - for testing
#  - for running all the "update" tasks like brewup etc
# FIXME: How report newly installed brews, casks, pips, npms, gems, etc. that aren't in this file.


# FIXME: Add:
# sudo echo /usr/local/bin/bash >> /etc/shells
# npm install -g git-guilt
# gem install bundler
# gem install bundler-audit

# FIXME: Add installation of bashhub - via pipx?

# FIXME: ansible-role-dotfiles!

# FIXME: GT FIXMEs in:
#./roles/darwin/vars/main.yml:  ComputerName: "discovery"  # osx-computername # FIXME: Set per computer, or use to identify host!
# https://github.com/lafarer/ansible-role-osx-computername/blob/master/tasks/main.yml

# FIXME: Move brewup, gemupdate to here?

# FIXME: Eventually Look up roles for redhat/debian stuff similar to macos stuff

# FIXME: Can use same tag on multiple tasks to group tasks.

# FIXME: Can use prompts

# FIXME:
#
# https://github.com/fubarhouse/ansible-role-macdock
# https://github.com/danbohea/ansible-role-macos-dock
# https://galaxy.ansible.com/danbohea/flux - flux configuration?
# https://galaxy.ansible.com/shashikant86/ios-dev
# ansible Liquid Prompt ala drew-kun/ansible-ohmyzsh
# https://galaxy.ansible.com/bjoernalbers/sysctl
#https://github.com/feffi/ansible-macos-softwareupdate
#https://github.com/dotstrap/ansible-xcode
#https://github.com/ansible/ansible-modules-extras/blob/devel/system/osx_defaults.py
#
#https://github.com/mego22/ansible-role-osx-settings
#
#https://github.com/0x4e3/osx-bootstrap-defaults
#https://github.com/osxstrap/ansible-osx-user-picture
# https://en.gravatar.com/userimage/34741261/b37d9ade8b8cea564bc47268db650c84.jpg?size=200
#https://github.com/osxstrap/ansible-osx-software-update
# drew-kun/ansible-dnscrypt
# drew-kun/ansible-sshd
# drew-kun/ansible-macos_terminal

#all:
# https://github.com/feffi/ansible-macos-git-repos

#darwin:
# https://github.com/feffi/ansible-macos-standby

#darwin/firefly:
# https://github.com/feffi/ansible-macos-timemachine
