---
- name: Hostname - Get current ComputerName
  ansible.builtin.command: scutil --get ComputerName
  register: computername_result
  changed_when: false
  check_mode: false
  when: system.hostname.computername != None

- name: Hostname - Update ComputerName
  ansible.builtin.command: scutil --set ComputerName {{ system.hostname.computername }}
  become: true
  when: system.hostname.computername != None and (system.hostname.computername not in computername_result.stdout)

- name: Hostname - Get current HostName
  ansible.builtin.command: scutil --get HostName
  register: hostname_result
  changed_when: false
  failed_when: false
  check_mode: false
  when: system.hostname.hostname != None

- name: Hostname - Update HostName
  ansible.builtin.command: scutil --set HostName {{ system.hostname.hostname }}
  become: true
  # yamllint disable-line rule:line-length
  when: system.hostname.hostname != None and (hostname_result.failed or (system.hostname.hostname not in hostname_result.stdout)) # editorconfig-checker-disable-line

- name: Hostname - Get current LocalHostName
  ansible.builtin.command: scutil --get LocalHostName
  register: localhostname_result
  changed_when: false
  check_mode: false
  when: system.hostname.localhostname != None

- name: Hostname - Update LocalHostName
  ansible.builtin.command: scutil --set LocalHostName {{ system.hostname.localhostname }}
  become: true
  when: system.hostname.localhostname != None and (system.hostname.localhostname not in localhostname_result.stdout)
