---
- name: Run ospideal homebrew role.
  include_role:
    name: ospideal-homebrew
  tags: ['homebrew']

- name: Run ospideal mas role.
  include_role:
    name: ospideal-mas
  tags: ['mas']

- name: Run ospideal osx-user-picture role.
  include_role:
    name: ospideal-osx-user-picture
  tags: ['osx-user-picture']
