---

    - name: Reuse dictionary definition window.
      community.general.osx_defaults:
          domain: com.apple.Dictionary
          key: ProhibitNewWindowForRequest
          type: bool
          value: true
          state: present
