---

- name: Finder - Show hidden files
  community.general.osx_defaults:
      domain: com.apple.finder
      key: AppleShowAllFiles
      type: bool
      value: true
      state: present
  notify: Restart Finder

- name: Finder - Set new window target
  community.general.osx_defaults:
      domain: com.apple.finder
      key: NewWindowTarget
      type: string
      value: PfDe  # "PfHm" for Home directory, "PfDe" for Desktop.
  notify: Restart Finder

- name: Finder - Show extension warning
  community.general.osx_defaults:
      domain: com.apple.finder
      key: FXEnableExtensionChangeWarning
      type: bool
      value: false
  notify: Restart Finder

- name: Finder - Warn before emptying the trash
  community.general.osx_defaults:
      domain: com.apple.finder
      key: WarnOnEmptyTrash
      type: bool
      value: true
  notify: Restart Finder

- name: Finder - Keep folders on top when sorting by name
  community.general.osx_defaults:
      domain: com.apple.finder
      key: _FXSortFoldersFirst
      type: bool
      value: false
  notify: Restart Finder

- name: Finder - Show full path in finder titlebar
  community.general.osx_defaults:
      domain: com.apple.finder
      key: _FXShowPosixPathInTitle
      type: bool
      value: true
  notify: Restart Finder

- name: Finder - Show pathbar in bottom of finder
  community.general.osx_defaults:
      domain: com.apple.finder
      key: ShowPathbar
      type: bool
      value: true
  notify: Restart Finder

- name: Finder - Show statusbar
  community.general.osx_defaults:
      domain: com.apple.finder
      key: ShowStatusBar
      type: bool
      value: true
  notify: Restart Finder

- name: Finder - When performing a search, search the current folder by default
  community.general.osx_defaults:
      domain: com.apple.finder
      key: FXDefaultSearchScope
      type: string
      value: SCcf
  notify: Restart Finder

- name: Finder - Enable quit menu item
  community.general.osx_defaults:
      domain: com.apple.finder
      key: QuitMenuItem
      type: bool
      value: true
  notify: Restart Finder

- name: Finder - Default view style
  community.general.osx_defaults:
      domain: com.apple.finder
      key: FXPreferredViewStyle
      type: string
      value: clmv  # "icnv" for icon view, "clmv" for column view, "Flwv" for cover flow view.
  notify: Restart Finder

- name: Finder - Show external harddrives on desktop
  community.general.osx_defaults:
      domain: com.apple.finder
      key: ShowExternalHardDrivesOnDesktop
      type: bool
      value: true
  notify: Restart Finder

- name: Finder - Show harddrives on desktop
  community.general.osx_defaults:
      domain: com.apple.finder
      key: ShowHardDrivesOnDesktop
      type: bool
      value: true
  notify: Restart Finder

- name: Finder - Show mounted servers on desktop
  community.general.osx_defaults:
      domain: com.apple.finder
      key: ShowMountedServersOnDesktop
      type: bool
      value: true
  notify: Restart Finder

- name: Finder - Show removable media on desktop
  community.general.osx_defaults:
      domain: com.apple.finder
      key: ShowRemovableMediaOnDesktop
      type: bool
      value: true
  notify: Restart Finder
