---

    - name: Set Help Viewer windows to non-floating mode
      community.general.osx_defaults:
          domain: com.apple.helpviewer
          key: DevMode
          type: bool
          value: true
          state: present
