---

    - name: Reveal IP address, hostname, OS version, etc. when clicking the clock in the login window.
      community.general.osx_defaults:
          domain: com.apple.loginwindow
          key: AdminHostInfo
          type: string
          value: HostName
          state: present
