---
- name: Automatically quit printer app once the print jobs complete
  community.general.osx_defaults:
    domain: com.apple.print.PrintingPrefs
    key: Quit When Finished
    type: bool
    value: true
    state: present
