---

    - name: Don't auto-play videos when opened with QuickTime Player.
      community.general.osx_defaults:
          domain: com.apple.QuickTimePlayerX
          key: MGPlayMovieOnOpen
          type: bool
          value: false
          state: present
