---
- homebrew:
    name: "{{ item.name }}"
    state: present
  with_items:
    - node

- name: Install global nodejs packages.
  command: npm install --global {{ item.name }}
  with_items: "{{ nodejs_npm_global_packages }}"
