---
- name: Check pre-commit is installed and updated
  community.general.homebrew:
    name: [pre-commit]
    state: latest
  tags: [always]
# FIXME: Move this to after dotfiles installation!
# - name: Auto update all pre-commit hooks
#   ansible.builtin.command: ~/.local/bin/pre-commit-autoupdate
#   register: pre_commit_autoupdate
#   changed_when: false
#   tags: [always]
