---
- name: Check pre-commit is installed and updated
  community.general.homebrew:
    name: [pre-commit]
    state: latest

- name: Auto update all pre-commit hooks
  ansible.builtin.command: ~/.local/bin/pre-commit-autoupdate
  register: pre_commit_autoupdate
  changed_when: pre_commit_autoupdate.stdout.find('Updating') != -1
