---
# Based on https://github.com/geerlingguy/mac-dev-playbook/blob/master/.github/workflows/ci.yml.

######################################################################
## minute         0-59
## hour           0-23
## day of month   1-31
## month          1-12
## day of week    0-7
######################################################################

name: CI
on:
  schedule:
    - cron: 1 2 * * 3
  # Run workflow manually (without waiting for the cron to be called),
  # through the Github Actions Workflow page directly.
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Default is true.
      matrix:
        os:
          - macos-latest # currently macos-12
          - ubuntu-latest # currently ubuntu-20.04

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Uninstall GitHub Actions' built-in Homebrew.
        run: ./bin/remove_homebrew.sh

      - name: Uninstall GitHub Actions' built-in browser installs.
        run: |
          sudo rm -rf /Applications/Firefox.app /Applications/Google\ Chrome.app

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install test dependencies.
        run: ./bin/install_ci_dependencies.sh

      - name: Lint code.
        run: ./bin/lint.sh

      - name: Test the playbook.
        run: ./bin/ci.sh
        env:
          ANSIBLE_FORCE_COLOR: '1'

      - name: Idempotence check.
        run: ./bin/ci_idempotence.sh
        env:
          ANSIBLE_FORCE_COLOR: '1'
