---

name: Code Quality
# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  code-quality:
    name: Check code quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache gems
        uses: actions/cache@v2.1.4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-

      - name: 'Bundler Audit'
        uses: andrewmcodes/bundler-audit-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          exclude: "./.git/*"
          fail_on_error: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: "."
          pattern: "*.sh"
          reporter: github-pr-review
          shellcheck_flags: '--external-sources --format=gcc --shell=bash'

      - name: Yamllint Github Action
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_config_filepath: '.yamllint.yml'
          yamllint_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ansible-lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: "roles"

      - name: Run detect-secrets with reviewdog
        uses: reviewdog/action-detect-secrets@v0.4.2
        with:
          github_token: ${{ secrets.github_token }}
