---

name: Pull Requests

# yamllint disable-line rule:truthy
on: pull_request

jobs:

  code-quality:
    name: Check code quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: languagetool
        uses: reviewdog/action-languagetool@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          # Change reporter level if you need.
          level: warning

      - name: Dependabot Auto Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2.4
        with:
          github-token: ${{ secrets.github_token }}

      - name: Update TOC
        run: npx markdown-toc README.md -i

      - name: Commit and push if README changed
        run: |-
          git diff
          git config --global user.email "proinsias@users.noreply.github.com"
          git config --global user.name "Francis T. O'Donovan"
          git diff --quiet || (git add README.md && git commit -m "Updated README TOC")
          git push
