---
# Enable auto backup
- osx_defaults:
    domain: com.dayoneapp.dayone.plist
    key: AutoBackupEnabled
    type: bool
    value: true
    state: present

# Add a Stack with Recent Applications
- osx_defaults:
    domain: com.apple.dock
    key: persistent-others
    type: array-add
    value: '{ "tile-data" = { "list-type" = 1; }; "tile-type" = "recents-tile"; }'
    state: present

# Use Monday as the first day of the week
- osx_defaults:
    domain: NSGlobalDomain
    key: AppleFirstWeekday
    type: string
    value: '{gregorian = 2;}'
    state: present

# Save screenshots to the desktop
- osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "${HOME}/Desktop"
    state: present

# Set the size 18 by default
- osx_defaults:
    domain: com.apple.Terminal
    key: "NSWindow Frame NSFontPanel"
    type: string
    value: "929 42 445 105 0 0 1440 900"
    state: present
